/**
 * BR-175 — AI Quality & Learning Review Center constants.
 * Observation/review only. Never applies semantic output or edits production rules.
 */

const FEATURE_FLAGS = Object.freeze({
  CAPTURE_ENABLED_ENV: "ATLAS_AI_QUALITY_CAPTURE_ENABLED",
  MODE_ENV: "ATLAS_AI_QUALITY_MODE"
});

const MODES = Object.freeze({
  OFF: "OFF",
  OBSERVE: "OBSERVE",
  REVIEW: "REVIEW"
});

const CASE_STATUSES = Object.freeze({
  NEW: "NEW",
  REVIEWING: "REVIEWING",
  SEMANTIC_CORRECT: "SEMANTIC_CORRECT",
  LEGACY_CORRECT: "LEGACY_CORRECT",
  BOTH_WRONG: "BOTH_WRONG",
  EXPECTED_BEHAVIOR: "EXPECTED_BEHAVIOR",
  REGRESSION_CANDIDATE: "REGRESSION_CANDIDATE",
  RESOLVED: "RESOLVED",
  IGNORED: "IGNORED"
});

const SIGNAL_TYPES = Object.freeze({
  SEMANTIC_DISAGREEMENT: "SEMANTIC_DISAGREEMENT",
  SEMANTIC_LOW_CONFIDENCE: "SEMANTIC_LOW_CONFIDENCE",
  SEMANTIC_TIMEOUT: "SEMANTIC_TIMEOUT",
  SEMANTIC_INVALID_JSON: "SEMANTIC_INVALID_JSON",
  SEMANTIC_OBJECTION_MISSED: "SEMANTIC_OBJECTION_MISSED",
  REPEATED_QUESTION: "REPEATED_QUESTION",
  REPEATED_QUESTION_COMPLAINT: "REPEATED_QUESTION_COMPLAINT",
  HUMAN_CORRECTION: "HUMAN_CORRECTION",
  TAKEOVER_AFTER_ATLAS: "TAKEOVER_AFTER_ATLAS",
  ABANDONMENT_AFTER_REPETITION: "ABANDONMENT_AFTER_REPETITION",
  UNANSWERED_ELIGIBLE_INBOUND: "UNANSWERED_ELIGIBLE_INBOUND",
  HUMAN_REQUIRED_THEN_QUALIFICATION: "HUMAN_REQUIRED_THEN_QUALIFICATION",
  RESCHEDULE_NOT_ACTED: "RESCHEDULE_NOT_ACTED",
  FACT_OSCILLATION: "FACT_OSCILLATION",
  FRUSTRATION_MISUNDERSTANDING: "FRUSTRATION_MISUNDERSTANDING",
  FAQ_INTERRUPT_MISAPPLIED: "FAQ_INTERRUPT_MISAPPLIED",
  PREMATURE_HANDOFF: "PREMATURE_HANDOFF",
  APPOINTMENT_CONFIRMATION_MISMATCH: "APPOINTMENT_CONFIRMATION_MISMATCH"
});

const ATTENTION_SIGNALS = Object.freeze([
  SIGNAL_TYPES.REPEATED_QUESTION,
  SIGNAL_TYPES.REPEATED_QUESTION_COMPLAINT,
  SIGNAL_TYPES.HUMAN_CORRECTION,
  SIGNAL_TYPES.TAKEOVER_AFTER_ATLAS,
  SIGNAL_TYPES.ABANDONMENT_AFTER_REPETITION,
  SIGNAL_TYPES.UNANSWERED_ELIGIBLE_INBOUND,
  SIGNAL_TYPES.HUMAN_REQUIRED_THEN_QUALIFICATION,
  SIGNAL_TYPES.RESCHEDULE_NOT_ACTED,
  SIGNAL_TYPES.FACT_OSCILLATION,
  SIGNAL_TYPES.FRUSTRATION_MISUNDERSTANDING,
  SIGNAL_TYPES.FAQ_INTERRUPT_MISAPPLIED,
  SIGNAL_TYPES.PREMATURE_HANDOFF,
  SIGNAL_TYPES.APPOINTMENT_CONFIRMATION_MISMATCH
]);

const DISAGREEMENT_SIGNALS = Object.freeze([
  SIGNAL_TYPES.SEMANTIC_DISAGREEMENT,
  SIGNAL_TYPES.SEMANTIC_OBJECTION_MISSED
]);

const SEVERITIES = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH"
});

const SOURCE_ENGINES = Object.freeze({
  RECRUIT_AI_V2_SEMANTIC: "recruit_ai_v2_semantic",
  RECRUIT_AI_V2: "recruit_ai_v2",
  CONVERSATION_ENGINE: "conversation_engine"
});

const REVIEW_ACTIONS = Object.freeze({
  MARK_SEMANTIC_CORRECT: "mark_semantic_correct",
  MARK_LEGACY_CORRECT: "mark_legacy_correct",
  BOTH_WRONG: "both_wrong",
  DEFINE_EXPECTED_BEHAVIOR: "define_expected_behavior",
  CREATE_REGRESSION_CANDIDATE: "create_regression_candidate",
  IGNORE: "ignore"
});

const REGRESSION_STATUSES = Object.freeze({
  PROPOSED: "proposed",
  APPROVED: "approved",
  IMPLEMENTED: "implemented",
  VERIFIED: "verified",
  REJECTED: "rejected"
});

const PROPOSAL_STATUSES = Object.freeze({
  GENERATED: "GENERATED",
  REJECTED: "REJECTED",
  REVISION_REQUESTED: "REVISION_REQUESTED",
  REGRESSION_APPROVED: "REGRESSION_APPROVED"
});

const IMPLEMENTATION_STATUSES = Object.freeze({
  PROPOSED: "PROPOSED",
  AUTHORIZED: "AUTHORIZED",
  REJECTED: "REJECTED",
  IMPLEMENTED: "IMPLEMENTED",
  VERIFIED: "VERIFIED"
});

const LEARNING_ACTIONS = Object.freeze({
  GENERATE_PROPOSAL: "generate_proposal",
  REJECT_PROPOSAL: "reject_proposal",
  REQUEST_REVISION: "request_revision",
  APPROVE_REGRESSION: "approve_regression",
  PROPOSE_IMPLEMENTATION: "propose_implementation",
  AUTHORIZE_IMPLEMENTATION: "authorize_implementation",
  REJECT_IMPLEMENTATION: "reject_implementation",
  MARK_IMPLEMENTED: "mark_implemented",
  MARK_VERIFIED: "mark_verified",
  REOPEN: "reopen"
});

const RISK_LEVELS = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH"
});

const AUDIT_ACTIONS = Object.freeze({
  PLATFORM_CAPTURE_TOGGLED: "ai_quality.platform_capture_toggled",
  TENANT_PARTICIPATION_UPDATED: "ai_quality.tenant_participation_updated",
  CASE_REVIEWED: "ai_quality.case_reviewed",
  EXPECTED_BEHAVIOR_DEFINED: "ai_quality.expected_behavior_defined",
  REGRESSION_PROMOTED: "ai_quality.regression_promoted",
  CASE_IGNORED: "ai_quality.case_ignored",
  CASE_RESOLVED: "ai_quality.case_resolved",
  PROPOSAL_GENERATED: "ai_quality.proposal_generated",
  PROPOSAL_REJECTED: "ai_quality.proposal_rejected",
  REVISION_REQUESTED: "ai_quality.revision_requested",
  REGRESSION_APPROVED: "ai_quality.regression_approved",
  IMPLEMENTATION_PROPOSED: "ai_quality.implementation_proposed",
  IMPLEMENTATION_AUTHORIZED: "ai_quality.implementation_authorized",
  IMPLEMENTATION_REJECTED: "ai_quality.implementation_rejected",
  IMPLEMENTATION_IMPLEMENTED: "ai_quality.implementation_implemented",
  LEARNING_VERIFIED: "ai_quality.verified",
  LEARNING_REOPENED: "ai_quality.reopened"
});

const HIDDEN_REASONING_KEYS = Object.freeze([
  "chainOfThought",
  "chain_of_thought",
  "hiddenReasoning",
  "hidden_reasoning",
  "reasoning",
  "thinking",
  "scratchpad",
  "privateAnalysis",
  "private_analysis"
]);

const LOW_CONFIDENCE_THRESHOLD = 0.7;

module.exports = {
  FEATURE_FLAGS,
  MODES,
  CASE_STATUSES,
  SIGNAL_TYPES,
  ATTENTION_SIGNALS,
  DISAGREEMENT_SIGNALS,
  SEVERITIES,
  SOURCE_ENGINES,
  REVIEW_ACTIONS,
  REGRESSION_STATUSES,
  PROPOSAL_STATUSES,
  IMPLEMENTATION_STATUSES,
  LEARNING_ACTIONS,
  RISK_LEVELS,
  AUDIT_ACTIONS,
  HIDDEN_REASONING_KEYS,
  LOW_CONFIDENCE_THRESHOLD
};
