/**
 * Financial Intelligence constants (RC3 / BR-062+).
 */

const MODULE_ID = "financial-intelligence";
const MODULE_VERSION = "1.0.0";

const CURRENCY_TOLERANCE = 0.02;

const PREMIUM_SOURCES = Object.freeze({
  OFFICIAL_QUOTE: "OFFICIAL_QUOTE",
  REPRESENTATIVE_CONFIRMED: "REPRESENTATIVE_CONFIRMED",
  PRELIMINARY_ESTIMATE: "PRELIMINARY_ESTIMATE",
  MISSING: "MISSING"
});

const RISK_PROFILES = Object.freeze({
  NOT_COMPLETED: "NOT_COMPLETED",
  CONSERVATIVE: "CONSERVATIVE",
  MODERATE: "MODERATE",
  AGGRESSIVE: "AGGRESSIVE"
});

const EVALUATION_STATUSES = Object.freeze({
  DRAFT_MISSING_POLICY_DATA: "DRAFT_MISSING_POLICY_DATA",
  DRAFT_TERM_QUOTE_REQUIRED: "DRAFT_TERM_QUOTE_REQUIRED",
  DRAFT_TERM_CONFIRMATION_REQUIRED: "DRAFT_TERM_CONFIRMATION_REQUIRED",
  DRAFT_INVESTMENT_HORIZON_REQUIRED: "DRAFT_INVESTMENT_HORIZON_REQUIRED",
  DRAFT_RISK_PROFILE_REQUIRED: "DRAFT_RISK_PROFILE_REQUIRED",
  DRAFT_REPLACEMENT_REVIEW_REQUIRED: "DRAFT_REPLACEMENT_REVIEW_REQUIRED",
  READY_FOR_REPRESENTATIVE_REVIEW: "READY_FOR_REPRESENTATIVE_REVIEW",
  REPRESENTATIVE_ADJUSTED: "REPRESENTATIVE_ADJUSTED",
  CLIENT_DISCUSSION_VERSION: "CLIENT_DISCUSSION_VERSION",
  SUPERSEDED: "SUPERSEDED"
});

const SECTION_TITLE = "Possible Discussion Scenarios for the Primerica Representative";

module.exports = {
  MODULE_ID,
  MODULE_VERSION,
  CURRENCY_TOLERANCE,
  PREMIUM_SOURCES,
  RISK_PROFILES,
  EVALUATION_STATUSES,
  SECTION_TITLE
};
