/**
 * Sprint 12.2 Phase 1 — Appointment lifecycle and ownership vocabulary.
 * Extends Sprint 22 appointmentDomain constants without replacing them.
 */

const { APPOINTMENT_STATUSES, APPOINTMENT_OUTCOMES } = require("../../../core/configuration/appointmentDomain");

const APPOINTMENT_LIFECYCLE_STATES = Object.freeze({
  SCHEDULED: "scheduled",
  CONFIRMED: "confirmed",
  RESCHEDULED: "rescheduled",
  COMPLETED: "completed",
  NO_SHOW: "no_show",
  CANCELLED: "cancelled",
  RECRUITED: "recruited",
  BECAME_CLIENT: "became_client"
});

const ALLOWED_LIFECYCLE_TRANSITIONS = Object.freeze({
  [APPOINTMENT_LIFECYCLE_STATES.SCHEDULED]: [
    APPOINTMENT_LIFECYCLE_STATES.CONFIRMED,
    APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED,
    APPOINTMENT_LIFECYCLE_STATES.CANCELLED
  ],
  [APPOINTMENT_LIFECYCLE_STATES.CONFIRMED]: [
    APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED,
    APPOINTMENT_LIFECYCLE_STATES.COMPLETED,
    APPOINTMENT_LIFECYCLE_STATES.NO_SHOW,
    APPOINTMENT_LIFECYCLE_STATES.CANCELLED,
    APPOINTMENT_LIFECYCLE_STATES.RECRUITED,
    APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT
  ],
  [APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED]: [
    APPOINTMENT_LIFECYCLE_STATES.CONFIRMED,
    APPOINTMENT_LIFECYCLE_STATES.CANCELLED
  ],
  [APPOINTMENT_LIFECYCLE_STATES.COMPLETED]: [],
  [APPOINTMENT_LIFECYCLE_STATES.NO_SHOW]: [
    APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED,
    APPOINTMENT_LIFECYCLE_STATES.CANCELLED
  ],
  [APPOINTMENT_LIFECYCLE_STATES.CANCELLED]: [],
  [APPOINTMENT_LIFECYCLE_STATES.RECRUITED]: [],
  [APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT]: []
});

const LIFECYCLE_TO_PERSISTENCE = Object.freeze({
  [APPOINTMENT_LIFECYCLE_STATES.SCHEDULED]: {
    status: APPOINTMENT_STATUSES.SCHEDULED,
    outcome: null
  },
  [APPOINTMENT_LIFECYCLE_STATES.CONFIRMED]: {
    status: APPOINTMENT_STATUSES.CONFIRMED,
    outcome: null
  },
  [APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED]: {
    status: APPOINTMENT_STATUSES.RESCHEDULED,
    outcome: null
  },
  [APPOINTMENT_LIFECYCLE_STATES.COMPLETED]: {
    status: APPOINTMENT_STATUSES.COMPLETED,
    outcome: null
  },
  [APPOINTMENT_LIFECYCLE_STATES.NO_SHOW]: {
    status: APPOINTMENT_STATUSES.NO_SHOW,
    outcome: APPOINTMENT_OUTCOMES.NO_SHOW
  },
  [APPOINTMENT_LIFECYCLE_STATES.CANCELLED]: {
    status: APPOINTMENT_STATUSES.CANCELLED,
    outcome: APPOINTMENT_OUTCOMES.CANCELLED
  },
  [APPOINTMENT_LIFECYCLE_STATES.RECRUITED]: {
    status: APPOINTMENT_STATUSES.COMPLETED,
    outcome: APPOINTMENT_OUTCOMES.RECRUITED
  },
  [APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT]: {
    status: APPOINTMENT_STATUSES.COMPLETED,
    outcome: APPOINTMENT_OUTCOMES.CLIENT
  }
});

const LIFECYCLE_HISTORY_TYPES = Object.freeze({
  [APPOINTMENT_LIFECYCLE_STATES.SCHEDULED]: "created",
  [APPOINTMENT_LIFECYCLE_STATES.CONFIRMED]: "confirmed",
  [APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED]: "rescheduled",
  [APPOINTMENT_LIFECYCLE_STATES.COMPLETED]: "completed",
  [APPOINTMENT_LIFECYCLE_STATES.NO_SHOW]: "no_show",
  [APPOINTMENT_LIFECYCLE_STATES.CANCELLED]: "cancelled",
  [APPOINTMENT_LIFECYCLE_STATES.RECRUITED]: "recruited",
  [APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT]: "became_client"
});

function isTerminalLifecycleState(state) {
  return [
    APPOINTMENT_LIFECYCLE_STATES.COMPLETED,
    APPOINTMENT_LIFECYCLE_STATES.CANCELLED,
    APPOINTMENT_LIFECYCLE_STATES.RECRUITED,
    APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT
  ].includes(state);
}

function canTransitionLifecycle(fromState, toState) {
  if (!fromState || !toState || fromState === toState) {
    return false;
  }

  return (ALLOWED_LIFECYCLE_TRANSITIONS[fromState] || []).includes(toState);
}

function resolveLifecycleState(appointment = {}) {
  if (!appointment) {
    return null;
  }

  const lifecycleFromMetadata = appointment.metadata?.lifecycleState;

  if (
    lifecycleFromMetadata &&
    Object.values(APPOINTMENT_LIFECYCLE_STATES).includes(lifecycleFromMetadata)
  ) {
    return lifecycleFromMetadata;
  }

  if (appointment.status === APPOINTMENT_STATUSES.CANCELLED) {
    return APPOINTMENT_LIFECYCLE_STATES.CANCELLED;
  }

  if (appointment.status === APPOINTMENT_STATUSES.NO_SHOW) {
    return APPOINTMENT_LIFECYCLE_STATES.NO_SHOW;
  }

  if (appointment.outcome === APPOINTMENT_OUTCOMES.RECRUITED) {
    return APPOINTMENT_LIFECYCLE_STATES.RECRUITED;
  }

  if (appointment.outcome === APPOINTMENT_OUTCOMES.CLIENT) {
    return APPOINTMENT_LIFECYCLE_STATES.BECAME_CLIENT;
  }

  if (appointment.outcome === APPOINTMENT_OUTCOMES.NO_SHOW) {
    return APPOINTMENT_LIFECYCLE_STATES.NO_SHOW;
  }

  if (appointment.status === APPOINTMENT_STATUSES.RESCHEDULED) {
    return APPOINTMENT_LIFECYCLE_STATES.RESCHEDULED;
  }

  if (appointment.status === APPOINTMENT_STATUSES.CONFIRMED) {
    return APPOINTMENT_LIFECYCLE_STATES.CONFIRMED;
  }

  if (appointment.status === APPOINTMENT_STATUSES.COMPLETED) {
    return APPOINTMENT_LIFECYCLE_STATES.COMPLETED;
  }

  if (appointment.status === APPOINTMENT_STATUSES.SCHEDULED) {
    return APPOINTMENT_LIFECYCLE_STATES.SCHEDULED;
  }

  return APPOINTMENT_LIFECYCLE_STATES.SCHEDULED;
}

module.exports = {
  APPOINTMENT_LIFECYCLE_STATES,
  ALLOWED_LIFECYCLE_TRANSITIONS,
  LIFECYCLE_TO_PERSISTENCE,
  LIFECYCLE_HISTORY_TYPES,
  isTerminalLifecycleState,
  canTransitionLifecycle,
  resolveLifecycleState
};
