/**
 * BR-186 — IUL / Policy Review Pipeline V2 constants.
 * Revenue-side operating layer. Separate from recruiting and Policy Intelligence.
 */

const POLICY_REVIEW_STAGES = Object.freeze({
  NEW_REVIEW_LEAD: "NEW_REVIEW_LEAD",
  REVIEW_REQUESTED: "REVIEW_REQUESTED",
  QUALIFIED: "QUALIFIED",
  APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
  DOCUMENTS_REQUESTED: "DOCUMENTS_REQUESTED",
  DOCUMENTS_RECEIVED: "DOCUMENTS_RECEIVED",
  REVIEW_COMPLETED: "REVIEW_COMPLETED",
  KEEP_CURRENT: "KEEP_CURRENT",
  ADJUST_CURRENT: "ADJUST_CURRENT",
  REPLACEMENT_OPPORTUNITY: "REPLACEMENT_OPPORTUNITY",
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  PLACED: "PLACED",
  NOT_PROCEEDING: "NOT_PROCEEDING"
});

const POLICY_REVIEW_OUTCOMES = Object.freeze({
  KEEP_CURRENT: POLICY_REVIEW_STAGES.KEEP_CURRENT,
  ADJUST_CURRENT: POLICY_REVIEW_STAGES.ADJUST_CURRENT,
  REPLACEMENT_OPPORTUNITY: POLICY_REVIEW_STAGES.REPLACEMENT_OPPORTUNITY,
  NOT_PROCEEDING: POLICY_REVIEW_STAGES.NOT_PROCEEDING
});

const POLICY_REVIEW_SCOPES = Object.freeze({
  MINE: "mine",
  TEAM: "team"
});

const POLICY_REVIEW_HISTORY_TYPES = Object.freeze({
  CREATED: "created",
  STAGE_CHANGED: "stage_changed",
  REVIEW_COMPLETED: "review_completed",
  OUTCOME_RECORDED: "outcome_recorded",
  APPOINTMENT_LINKED: "appointment_linked",
  DOCUMENTS_REQUESTED: "documents_requested",
  DOCUMENTS_RECEIVED: "documents_received",
  APPLICATION_SUBMITTED: "application_submitted",
  PLACED: "placed",
  ATTRIBUTION_SET: "attribution_set",
  PRODUCTION_UPDATED: "production_updated"
});

const POLICY_REVIEW_ALLOWED_TRANSITIONS = Object.freeze({
  [POLICY_REVIEW_STAGES.NEW_REVIEW_LEAD]: [
    POLICY_REVIEW_STAGES.REVIEW_REQUESTED,
    POLICY_REVIEW_STAGES.QUALIFIED,
    POLICY_REVIEW_STAGES.APPOINTMENT_BOOKED,
    POLICY_REVIEW_STAGES.DOCUMENTS_REQUESTED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.REVIEW_REQUESTED]: [
    POLICY_REVIEW_STAGES.QUALIFIED,
    POLICY_REVIEW_STAGES.APPOINTMENT_BOOKED,
    POLICY_REVIEW_STAGES.DOCUMENTS_REQUESTED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.QUALIFIED]: [
    POLICY_REVIEW_STAGES.APPOINTMENT_BOOKED,
    POLICY_REVIEW_STAGES.DOCUMENTS_REQUESTED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.APPOINTMENT_BOOKED]: [
    POLICY_REVIEW_STAGES.DOCUMENTS_REQUESTED,
    POLICY_REVIEW_STAGES.DOCUMENTS_RECEIVED,
    POLICY_REVIEW_STAGES.REVIEW_COMPLETED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.DOCUMENTS_REQUESTED]: [
    POLICY_REVIEW_STAGES.DOCUMENTS_RECEIVED,
    POLICY_REVIEW_STAGES.REVIEW_COMPLETED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.DOCUMENTS_RECEIVED]: [
    POLICY_REVIEW_STAGES.REVIEW_COMPLETED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.REVIEW_COMPLETED]: [
    POLICY_REVIEW_STAGES.KEEP_CURRENT,
    POLICY_REVIEW_STAGES.ADJUST_CURRENT,
    POLICY_REVIEW_STAGES.REPLACEMENT_OPPORTUNITY,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.KEEP_CURRENT]: [],
  [POLICY_REVIEW_STAGES.ADJUST_CURRENT]: [
    POLICY_REVIEW_STAGES.APPLICATION_SUBMITTED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.REPLACEMENT_OPPORTUNITY]: [
    POLICY_REVIEW_STAGES.APPLICATION_SUBMITTED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.APPLICATION_SUBMITTED]: [
    POLICY_REVIEW_STAGES.PLACED,
    POLICY_REVIEW_STAGES.NOT_PROCEEDING
  ],
  [POLICY_REVIEW_STAGES.PLACED]: [],
  [POLICY_REVIEW_STAGES.NOT_PROCEEDING]: []
});

const POLICY_REVIEW_LIST_COLUMNS = Object.freeze([
  "id",
  "organization_id",
  "client_id",
  "owner_user_id",
  "contact_id",
  "service_case_id",
  "appointment_id",
  "document_request_id",
  "production_id",
  "linked_prospect_id",
  "stage",
  "language",
  "state",
  "source",
  "campaign",
  "ad_id",
  "adset_id",
  "creative_id",
  "campaign_intake_code",
  "stage_timestamps",
  "carrier_product_label",
  "monthly_premium",
  "annualized_premium",
  "submission_date",
  "placed_date",
  "commission_level_pct",
  "paid_advance_factor_pct",
  "estimated_take_home",
  "actual_paid_commission",
  "created_at",
  "updated_at"
]);

const COMMISSION_LABELS = Object.freeze({
  ESTIMATED: "ESTIMATED",
  ACTUAL: "ACTUAL"
});

module.exports = {
  POLICY_REVIEW_STAGES,
  POLICY_REVIEW_OUTCOMES,
  POLICY_REVIEW_SCOPES,
  POLICY_REVIEW_HISTORY_TYPES,
  POLICY_REVIEW_ALLOWED_TRANSITIONS,
  POLICY_REVIEW_LIST_COLUMNS,
  COMMISSION_LABELS
};
