/**
 * BR-233 — National U.S. locality resolver constants.
 * Tenant coverage lists are not a parser dictionary. Puerto Rico is excluded.
 */

"use strict";

const US_STATE_NAME_TO_ABBR = Object.freeze({
  alabama: "AL",
  al: "AL",
  alaska: "AK",
  ak: "AK",
  arizona: "AZ",
  az: "AZ",
  arkansas: "AR",
  ar: "AR",
  california: "CA",
  ca: "CA",
  colorado: "CO",
  co: "CO",
  connecticut: "CT",
  ct: "CT",
  delaware: "DE",
  de: "DE",
  "district of columbia": "DC",
  dc: "DC",
  florida: "FL",
  fl: "FL",
  georgia: "GA",
  ga: "GA",
  hawaii: "HI",
  hi: "HI",
  idaho: "ID",
  id: "ID",
  illinois: "IL",
  il: "IL",
  indiana: "IN",
  in: "IN",
  iowa: "IA",
  ia: "IA",
  kansas: "KS",
  ks: "KS",
  kentucky: "KY",
  ky: "KY",
  louisiana: "LA",
  la: "LA",
  maine: "ME",
  me: "ME",
  maryland: "MD",
  md: "MD",
  massachusetts: "MA",
  ma: "MA",
  michigan: "MI",
  mi: "MI",
  minnesota: "MN",
  mn: "MN",
  mississippi: "MS",
  ms: "MS",
  missouri: "MO",
  mo: "MO",
  montana: "MT",
  mt: "MT",
  nebraska: "NE",
  ne: "NE",
  nevada: "NV",
  nv: "NV",
  "new hampshire": "NH",
  "nueva hampshire": "NH",
  nh: "NH",
  "new jersey": "NJ",
  "nueva jersey": "NJ",
  nj: "NJ",
  "new mexico": "NM",
  "nuevo mexico": "NM",
  nm: "NM",
  "new york": "NY",
  "nueva york": "NY",
  ny: "NY",
  "north carolina": "NC",
  "norte carolina": "NC",
  "carolina del norte": "NC",
  nc: "NC",
  "north dakota": "ND",
  "dakota del norte": "ND",
  nd: "ND",
  ohio: "OH",
  oh: "OH",
  oklahoma: "OK",
  ok: "OK",
  oregon: "OR",
  or: "OR",
  pennsylvania: "PA",
  pa: "PA",
  "rhode island": "RI",
  ri: "RI",
  "south carolina": "SC",
  "sur carolina": "SC",
  "carolina del sur": "SC",
  sc: "SC",
  "south dakota": "SD",
  "dakota del sur": "SD",
  sd: "SD",
  tennessee: "TN",
  tn: "TN",
  texas: "TX",
  tx: "TX",
  utah: "UT",
  ut: "UT",
  vermont: "VT",
  vt: "VT",
  virginia: "VA",
  va: "VA",
  washington: "WA",
  wa: "WA",
  "west virginia": "WV",
  "virginia occidental": "WV",
  wv: "WV",
  wisconsin: "WI",
  wi: "WI",
  wyoming: "WY",
  wy: "WY"
});

const US_POSTAL_ABBREVIATIONS = new Set(Object.values(US_STATE_NAME_TO_ABBR));

const EXCLUDED_TERRITORY_TOKENS = Object.freeze({
  pr: true,
  "puerto rico": true,
  as: true,
  "american samoa": true,
  gu: true,
  guam: true,
  mp: true,
  "northern mariana islands": true,
  vi: true,
  "virgin islands": true,
  "us virgin islands": true
});

const FALSE_POSITIVE_STATE_TOKENS = new Set([
  "me",
  "in",
  "or",
  "ok",
  "la",
  "ma",
  "pa",
  "id",
  "hi",
  "de",
  "al"
]);

const PLACE_NAME_SUFFIXES = [
  " census designated place",
  " cdp",
  " city",
  " town",
  " village",
  " borough",
  " municipality",
  " consolidated government",
  " metro government",
  " metropolitan government",
  " unified government",
  " zona urbana",
  " comunidad"
];

const FIPS_TO_USPS = Object.freeze({
  "01": "AL",
  "02": "AK",
  "04": "AZ",
  "05": "AR",
  "06": "CA",
  "08": "CO",
  "09": "CT",
  "10": "DE",
  "11": "DC",
  "12": "FL",
  "13": "GA",
  "15": "HI",
  "16": "ID",
  "17": "IL",
  "18": "IN",
  "19": "IA",
  "20": "KS",
  "21": "KY",
  "22": "LA",
  "23": "ME",
  "24": "MD",
  "25": "MA",
  "26": "MI",
  "27": "MN",
  "28": "MS",
  "29": "MO",
  "30": "MT",
  "31": "NE",
  "32": "NV",
  "33": "NH",
  "34": "NJ",
  "35": "NM",
  "36": "NY",
  "37": "NC",
  "38": "ND",
  "39": "OH",
  "40": "OK",
  "41": "OR",
  "42": "PA",
  "44": "RI",
  "45": "SC",
  "46": "SD",
  "47": "TN",
  "48": "TX",
  "49": "UT",
  "50": "VT",
  "51": "VA",
  "53": "WA",
  "54": "WV",
  "55": "WI",
  "56": "WY"
});

const COMPLETENESS = Object.freeze({
  COMPLETE: "complete",
  PARTIAL: "partial",
  STATE_ONLY: "state_only",
  NONE: "none"
});

const CONFIDENCE = Object.freeze({
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low"
});

const RESOLUTION_SOURCE = Object.freeze({
  GAZETTEER: "gazetteer",
  ZIP_CROSSWALK: "zip_crosswalk",
  ALIAS_OVERLAY: "alias_overlay",
  AMBIGUOUS: "ambiguous",
  NONE: "none"
});

module.exports = {
  US_STATE_NAME_TO_ABBR,
  US_POSTAL_ABBREVIATIONS,
  EXCLUDED_TERRITORY_TOKENS,
  FALSE_POSITIVE_STATE_TOKENS,
  PLACE_NAME_SUFFIXES,
  FIPS_TO_USPS,
  COMPLETENESS,
  CONFIDENCE,
  RESOLUTION_SOURCE
};
